"""add ingestion tracking to documents

Revision ID: fb2474e23c11
Revises: 9b7dd1e6b35e
Create Date: 2026-02-11 13:46:50.728907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2474e23c11'
down_revision: Union[str, Sequence[str], None] = '9b7dd1e6b35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('storage_path', sa.String(length=1024), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
